CC=g++ -g -Wall

# List of source files for your pager
PAGER_SOURCES=globals.cpp vm_pager.cpp

# Generate the names of the pager's object files
PAGER_OBJS=${PAGER_SOURCES:.cpp=.o}
tests = test3.4 test14.8 test15.8 test21.4 test23.4 test24.4 test29.8
all: pager app $(tests)

# Compile the pager and tag this compilation
pager: ${PAGER_OBJS} libvm_pager.o
	./autotag.sh
	${CC} -o $@ $^

# Compile an application program
$(tests):
 %: %.cpp libvm_app.o
	${CC} -o $@ $^ -ldl

app: test3.4.cpp libvm_app.o
	${CC} -o $@ $^ -ldl

# Generic rules for compiling a source file to an object file
%.o: %.cpp
	${CC} -c $<
%.o: %.cc
	${CC} -c $<

clean:
	rm -f ${PAGER_OBJS} pager app $(tests)
